### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by pennybuster** [VirtuBox/easyengine-dashboard#2]
Hi there! Thank you for sharing useful stuff for EasyEngine.
Please consider the following suggestions for this dashboard:
- Adminer instead of PHPMyAdmin:
https://www.wpoven.com/blog/adminer-vs-phpmyadmin
https://www.adminer.org/en/phpmyadmin/
- KodExplorer instead of eXtplorer:
https://github.com/kalcaddle/KodExplorer
http://demo.kodcloud.com/
- Two-/Multi- Factor Authenication:
https://github.com/Daplie/browser-authenticator
https://daplie.github.io/browser-authenticator/
Thanks a million!!!!!

**Comment by VirtuBox** [comment]
Hello @pennybuster,

Adminer is already available in the database tab.
About KodExplorer, I will take a look, but it seems to be pretty heavy compared to eXplorer.
For the 2-FA Authentication, isn't it too much to protect access to services with login/password required ?

**Comment by pennybuster** [comment]
Thanks for your reply. About 2FA, login information can be intercepted for example if a Windows machine is infected with a trojan. This looks awesome: https://github.com/clems4ever/authelia because it also supports SSO for multiple backends. I haven't tried it.

**Comment by VirtuBox** [comment]
Hello @pennybuster, 
thanks for the suggestion, I will take a look on the configuration of authelia to see if it can be easily installed. 
About using another file manager than eXtplorer, I'm planning to replace it with [droppy](https://droppy.silverwind.io/#/), it's the best file manager I have found at the moment, and it can be installed easily.
